replicas: 1

credentials:
  user: "vulas"
  password: "vulas"

path: /monitoring/grafana

rbac:
  create: true
  namespaced: false

persistentVolume:
  enabled: true
  storage: "1Gi"

image:
  initContainer:
    registry: {}
    registryPort: {}
    name: "busybox"
    tag: "1.31.0"
    pullpolicy: "IfNotPresent"
    resources:
  limits:
    cpu: "50m"
    memory: "100Mi"

  securityContext:
    runAsUser: 12000

  mainContainer:
    registry: {}
    registryPort: {}
    name: "grafana/grafana"
    tag: "6.4.3"
    pullpolicy: "IfNotPresent"
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"

    livenessProbe:
      # Overall time before container is killed by k8s :
      # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * failureThreshold)
      # = 775s ~= 13min
      enabled: false
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5

    readinessProbe:
      # Overall time before container is considered unready by k8s :
      # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * successThreshold)
      # = 205s ~= 3.5min
      enabled: false
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5
