# _n_ replicas
replicas: 1

credentials:
  user: "vulas"
  password: "vulas"

path: /monitoring/grafana

rbac:
  # _n_ rbac.create
  create: true
  # _n_ rbac.namespaced
  namespaced: false

persistentVolume:
  # _n_ persistentVolume.enabled
  enabled: true
  # _n_ persistentVolume.storage
  storage: "1Gi"

image:
  initContainer:
    # _n_ image.initContainer.registry
    registry: {}
    # _n_ image.initContainer.registryPort
    registryPort: {}
    # _n_ image.initContainer.name
    name: "busybox"
    # _n_ image.initContainer.tag
    tag: "1.31.0"
    # _n_ image.initContainer.pullpolicy
    pullpolicy: "IfNotPresent"
    # _n_ image.initContainer.resources
    resources:
      limits:
        cpu: "50m"
        memory: "100Mi"

  securityContext:
    # _n_ image.securityContext.runAsUser
    runAsUser: 12000

  mainContainer:
    # _n_ image.mainContainer.registry
    registry: {}
    # _n_ image.mainContainer.registryPort
    registryPort: {}
    # _n_ image.mainContainer.name
    name: "grafana/grafana"
    # _n_ image.mainContainer.tag
    tag: "master"
    # _n_ image.mainContainer.pullpolicy
    pullpolicy: "IfNotPresent"
    # _n_ image.mainContainer.resources
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"

    livenessProbe:
      # _n_ image.mainContainer.livenessProbe.enabled
      # _i_
      # Overall time before container is killed by k8s :
      # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * failureThreshold)
      # = 775s ~= 13min
      enabled: false
      # _n_ image.mainContainer.livenessProbe.initialDelaySeconds
      initialDelaySeconds: 5
      # _n_ image.mainContainer.livenessProbe.periodSeconds
      periodSeconds: 30
      # _n_ image.mainContainer.livenessProbe.timeoutSeconds
      timeoutSeconds: 5
      # _n_ image.mainContainer.livenessProbe.failureThreshold
      failureThreshold: 5

    readinessProbe:
      # _n_ image.mainContainer.readinessProbe.enabled
      # _i_
      # Overall time before container is considered unready by k8s :
      # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * successThreshold)
      # = 205s ~= 3.5min
      enabled: false
      # _n_ image.mainContainer.readinessProbe.initialDelaySeconds
      initialDelaySeconds: 5
      # _n_ image.mainContainer.readinessProbe.periodSeconds
      periodSeconds: 30
      # _n_ image.mainContainer.readinessProbe.timeoutSeconds
      timeoutSeconds: 5
      # _n_ image.mainContainer.readinessProbe.failureThreshold
      failureThreshold: 5
