language: java

jdk:
  - openjdk8

branches:
  except:
    - gh-pages

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false

sudo: false

script: mvn -Dtest=AllExceptSlowTests -B clean install