language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - oracle-java8-installer # Updates JDK 8 to the latest available.

branches:
  except:
    - gh-pages

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false

sudo: false

script: mvn -DskipTests -B clean install