language: java

jdk:
  - openjdk8

branches:
  except:
    - gh-pages

cache:
  timeout: 1000
  directories:
  - $HOME/.m2

before_cache:
 - rm -rf $HOME/.m2/repository/com/sap/research/security/vulas/

notifications:
  email: false

sudo: false

script: mvn -e -B clean install