matrix:
  include:
    - language: java
      jdk: openjdk8
      cache:
        timeout: 1000
        directories:
        - $HOME/.m2
      before_cache:
        - rm -rf $HOME/.m2/repository/com/sap/research/security/vulas/
      install:
        - "echo 'Skipping install stage, dependencies will be downloaded during build and test stages.'"
      script: mvn -e -B -P soot,gradle -Dit.test='!IT01_PatchAnalyzerIT, IT*, *IT, *ITCase' -DfailIfNoTests=false --settings .travis/settings.xml clean install
    - language: java
      jdk: oraclejdk8
      cache:
        timeout: 1000
        directories:
        - $HOME/.m2
      before_cache:
        - rm -rf $HOME/.m2/repository/com/sap/research/security/vulas/
      install:
        - "echo 'Skipping install stage, dependencies will be downloaded during build and test stages.'"
      script: mvn -e -B -P soot,gradle -Dit.test='!IT01_PatchAnalyzerIT, IT*, *IT, *ITCase' -DfailIfNoTests=false --settings .travis/settings.xml clean install 
branches:
  except:
    - gh-pages

notifications:
  email: false
