apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "mountedConfigMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  entrypoint.sh: |-
    FLYWAY_OPTS="-Dflyway.skipDefaultCallbacks=true"

    java \
        -Dvulas.jira.usr=$JIRA_USER \
        -Dvulas.jira.pwd=$JIRA_PASSWORD \
        $FLYWAY_OPTS \
        -Dspring.profiles.active=docker \
        -jar /vulas/rest-backend.jar

  postgres-checker.sh: |-
    #!/bin/sh
    VULAS_CHART="{{ template "name" . }}"
    VULAS_LOG_ORIGIN="postgres-checker.sh"
    {{- include "logFunctions" . | nindent 4 }}

    {{- $release := .Release.Name }}
    until pg_isready -q -h {{ $release }}-db-master -p 5432; do
      _vulas_info "Postgres-master not ready, sleeping for {{ .Values.backoffDuration }}"
      sleep {{ .Values.backoffDuration }}
    done
    _vulas_info "Postgres master is ready"

    until pg_isready -q -h {{ $release }}-db-pool -p 5432; do
      _vulas_info "Pgpool entrypoint not ready, sleeping for {{ .Values.backoffDuration }}"
      sleep {{ .Values.backoffDuration }}
    done
    _vulas_info "Pgpool is ready"
    exit 0

  replica-checker.sh: |-
    #!/bin/sh
    {{- if .Values.rbac.create }}
    VULAS_CHART="{{ template "name" . }}"
    VULAS_LOG_ORIGIN="restbackend-checker.sh"
    {{- include "logFunctions" . | nindent 4 }}

    KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    RESPONSE=false
    {{- with .Values.global }}
    {{- $replica := (mul .masterReplicas .replicationFactor) | default .slaveReplicas }}
    until $RESPONSE; do
      READY_REPLICAS=$(curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/{{ .namespace }}/endpoints/{{ $release }}-db-slave | jq '.subsets[].addresses | length ')
      _vulas_info "Found ${READY_REPLICAS} postgres replicas ready"
      if [ $READY_REPLICAS -ge {{ $replica }} ]; then
        _vulas_info "All replica nodes are ready"
        exit 0
      fi
    {{- end }}
      _vulas_info "Replication nodes are not ready, sleeping for {{ .Values.backoffDuration }}"
      sleep {{ .Values.backoffDuration }}
    done
    {{- else }}
    _vulas_info "Sleeping 120s to ensure that replication is set up"
    sleep 120
    {{- end }}
    exit 0
