apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "configMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  {{- if .Values.debug }}
  VULAS_DEBUG: "true"
  {{- end }}

  {{- if .Values.extraConfigs }}
  {{- toYaml .Values.extraConfigs | nindent 2 }}
  {{- end }}
