apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "mountedConfigMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  nginx-init.sh: |-
    #!/bin/sh
    VULAS_CHART="{{ template "name" . }}"
    VULAS_LOG_ORIGIN="permission-fix.sh"
    {{- include "logFunctions" . | nindent 4}}

    {{- with .Values.ingressController }}
    {{- if .persistentVolume }}
    {{- if .persistentVolume.cache }}
    {{- if .persistentVolume.cache.enabled }}
    _vulas_log "Fixing permission pvc permission"
    chown -R {{ .image.runAsUser }}:{{ .image.runAsUser }} {{ .persistentVolume.mountPath }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    exit 0
