global:
    dbCredentials:
        pool_password: changeme
        pool_user: pgpool
        postgres_db: vulas
        postgres_password: changeme
        postgres_user: postgres
        replication_user: replication
    env: TESTING
    existingClaim: {}
    ingress:
        class: nginx
        enabled: true
    masterReplicas: 1
    namespace: vulnerability-assessment-tool-core
    podPriorityClass:
        enabled: true
    projectName: vulnerability-assessment-tool
    replicationFactor: 2
    slaveReplicas: 2
