apiVersion: v1
appVersion: "1.0"

description: A Chart for patch-lib-analyzer
name: patchlibanalyzer
version: 0.1.0

keywords:
  - "vulas"
  - "open-source"
  - "security-tools"
  - "java"
  - "python"
  - "maven"
  - "gradle"

home: https://sap.github.io/vulnerability-assessment-tool/
sources:
  - https://github.com/SAP/vulnerability-assessment-tool

maintainers:
  - name: "Quoc Trung HOANG"
    email: "quoc.trung.hoang@sap.com"
    url: ""

kubeVersion: ">=v1.15.0"
engine: gotpl
tillerVersion: "v2.14.2"
