rbac:
  create: true

kubeStateMetrics:
  enabled: true
  replicas: 1

  selfAntiAffinity:
    soft: true
    weight: 100

  image:
    pullPolicy: "IfNotPresent"
    registry: quay.io
    registryPort: {}
    name: coreos/kube-state-metrics
    tag: "v1.7.2"

    livenessProbe:
      # Overall time before container is killed by k8s :
      # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * failureThreshold)
      # = 775s ~= 13min
      enabled: false
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5

    readinessProbe:
      # Overall time before container is considered unready by k8s :
      # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * successThreshold)
      # = 205s ~= 3.5min
      enabled: false
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5

    resources:
      limits:
        cpu: 40m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi

    securityContext:
      runAsUser: 65534

nodeExporter:
  enabled: true

  selfAntiAffinity:
    soft: true
    weight: 100

  image:
    pullPolicy: "IfNotPresent"
    registry: {}
    registryPort: {}
    name: prom/node-exporter
    tag: "v0.18.1"

    livenessProbe:
      # Overall time before container is killed by k8s :
      # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * failureThreshold)
      # = 775s ~= 13min
      enabled: false
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5

    readinessProbe:
      # Overall time before container is considered unready by k8s :
      # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * successThreshold)
      # = 205s ~= 3.5min
      enabled: false
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5

    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 30Mi

    securityContext: {}

  podSecurityPolicy:
    enabled: true
    ## If true, node-exporter pods share the host network namespace
    hostNetwork: true
    ## If true, node-exporter pods share the host PID namespace
    hostPID: true

server:
  path: "/monitoring/prometheus/"
  replicas: 1
  podManagementPolicy: "Parallel"
  enableAdminApi: true
  retention: "90d"

  selfAntiAffinity:
    soft: true
    weight: 100

  persistentVolume:
    enabled: false
    mountPath: /data
    storage: "2Gi"

  image:
    mainContainer:
      pullPolicy: "IfNotPresent"
      registry: {}
      registryPort: {}
      name: prom/prometheus
      tag: "v2.12.0"

      livenessProbe:
        # Overall time before container is killed by k8s :
        # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * failureThreshold)
        # = 775s ~= 13min
        enabled: false
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
        path: /healthy

      readinessProbe:
        # Overall time before container is considered unready by k8s :
        # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * successThreshold)
        # = 205s ~= 3.5min
        enabled: false
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
        path: /ready

      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      securityContext: {}
