apiVersion: v1
appVersion: "1.0"

description: A Chart for frontendapps
name: frontendapps
version: 0.1.0
appVersion: "3.1.7-SNAPSHOT"

keywords:
  - "vulas"

home: https://sap.github.io/vulnerability-assessment-tool/
sources:
  - https://github.com/SAP/vulnerability-assessment-tool

kubeVersion: ">=v1.15.0"
icon: file://tomcat.png
engine: gotpl
tillerVersion: "v2.14.2"
