{{- if .Values.defaultBackend.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "nginx-ingress.defaultBackend.mountedConfigMapName" . }}
  namespace: {{ .Values.global.coreNamespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log               /var/log/nginx/error.log warn;
    pid                     /var/run/nginx.pid;

    events {
      worker_connections    1024;
    }

    http {
      include               /etc/nginx/mime.types;
      default_type          application/octet-stream;
      access_log            off;
      sendfile              on;
      keepalive_timeout     65;
      server {
          listen            8080;
          server_name       localhost;
          access_log        off;

          location = /healthz {
            return 200;
          }

          location ~ ^/$ {
            return 301 https://sap.github.io/vulnerability-assessment-tool/;
          }

          location / {
            root   /usr/share/nginx/html;
          }
      }
    }

  browser.json: |-
    [
      {
          "text": "05 Jun 2019 – Port 8080 is successfully closed. <a target=\"_blank\" href=\"https://github.wdf.sap.corp/pages/vulas/sap-docs/user/support/faq_enterprise/#tlsssl-connections\">Read more here about how to switch to HTTPS</a>",
          "type": "Success",
          "active": false
      },
      {
          "text": "10 Apr 2019 - Vulas now runs on Converged Cloud. Please, open a <a target=\"_blank\" href=\"https://jtrack.wdf.sap.corp/browse/VULAS\">ticket</a> in case of issues",
          "type": "Success",
          "active": false
      },
      {
          "text": "15 Apr 2019 - The <a target=\"_blank\" href=\"https://github.wdf.sap.corp/pages/vulas/sap-docs/user/tutorials/workspace_howto/#create-workspace\">public workspace cannot be used any longer</a>",
          "type": "Error",
          "active": false
      }
    ]

{{- end -}}
